// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="control_SRAM_HLS_control_SRAM_HLS,hls_ip_2021_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu5p-flva2104-1-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=1.539429,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=63,HLS_SYN_LUT=340,HLS_VERSION=2021_2}" *)

module control_SRAM_HLS (
        ap_local_block,
        ap_local_deadlock,
        ap_clk,
        ap_rst,
        addr_in,
        data_in,
        data_out,
        we,
        re,
        ready_r,
        Addr,
        Dq_i,
        Dq_o,
        Ce_n,
        Ce2,
        Ce2_n,
        Oe_n,
        Rw_n,
        Ld_n,
        Cke_n,
        clk,
        reset
);

parameter    ap_ST_fsm_state1 = 1'd1;

output   ap_local_block;
output   ap_local_deadlock;
input   ap_clk;
input   ap_rst;
input  [18:0] addr_in;
input  [35:0] data_in;
output  [35:0] data_out;
input   we;
input   re;
output   ready_r;
output  [18:0] Addr;
input  [35:0] Dq_i;
output  [35:0] Dq_o;
output   Ce_n;
output   Ce2;
output   Ce2_n;
output   Oe_n;
output   Rw_n;
output   Ld_n;
output   Cke_n;
input   clk;
input   reset;

reg ready_r;
reg[35:0] Dq_o;
reg Ce_n;
reg Ce2;
reg Ce2_n;
reg Rw_n;
reg Ld_n;

reg   [2:0] next_state;
reg   [18:0] addr_reg_V;
reg   [35:0] data_out_reg_V;
reg   [0:0] dq_t;
reg   [2:0] state;
wire   [2:0] select_ln63_1_fu_326_p3;
reg   [2:0] ap_phi_mux_storemerge1_phi_fu_235_p4;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] reset_read_read_fu_104_p2;
wire   [2:0] state_load_load_fu_269_p1;
wire   [2:0] select_ln65_1_fu_281_p3;
reg   [0:0] ap_phi_mux_storemerge_phi_fu_244_p4;
reg   [2:0] ap_phi_mux_empty_phi_fu_256_p4;
wire   [2:0] select_ln64_1_fu_298_p3;
wire   [2:0] select_ln62_1_fu_361_p3;
wire   [2:0] zext_ln61_fu_397_p1;
reg   [2:0] ap_sig_allocacmp_next_state_load;
wire   [0:0] and_ln98_fu_460_p2;
wire   [0:0] and_ln96_fu_442_p2;
reg   [18:0] ap_sig_allocacmp_addr_reg_V_load;
reg   [35:0] ap_sig_allocacmp_data_out_reg_V_load;
reg   [0:0] ap_sig_allocacmp_dq_t_load;
wire   [0:0] dq_t_load_load_fu_482_p1;
wire   [0:0] or_ln61_fu_263_p0;
wire   [0:0] or_ln61_fu_263_p1;
wire   [0:0] select_ln65_fu_273_p0;
wire   [0:0] or_ln61_fu_263_p2;
wire   [2:0] select_ln65_fu_273_p3;
wire   [0:0] select_ln64_fu_290_p0;
wire   [2:0] select_ln64_fu_290_p3;
wire   [0:0] select_ln63_fu_318_p0;
wire   [2:0] select_ln63_fu_318_p3;
wire   [0:0] select_ln62_fu_353_p0;
wire   [2:0] select_ln62_fu_353_p3;
wire   [0:0] select_ln61_fu_381_p0;
wire   [1:0] select_ln61_fu_381_p3;
wire   [1:0] select_ln61_1_fu_389_p3;
wire   [0:0] icmp_ln96_fu_430_p2;
wire   [0:0] icmp_ln96_1_fu_436_p2;
wire   [0:0] icmp_ln98_fu_448_p2;
wire   [0:0] icmp_ln98_1_fu_454_p2;
reg   [0:0] ap_NS_fsm;
wire    ap_ST_fsm_state1_blk;
reg    ap_condition_101;
reg    ap_condition_77;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 next_state = 3'd0;
#0 addr_reg_V = 19'd0;
#0 data_out_reg_V = 36'd0;
#0 dq_t = 1'd1;
#0 state = 3'd1;
#0 ap_CS_fsm = 1'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if ((reset_read_read_fu_104_p2 == 1'd1)) begin
            addr_reg_V <= 19'd0;
        end else if ((1'b1 == ap_condition_101)) begin
            addr_reg_V <= addr_in;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if ((reset_read_read_fu_104_p2 == 1'd1)) begin
            data_out_reg_V <= 36'd0;
        end else if ((1'b1 == ap_condition_77)) begin
            data_out_reg_V <= Dq_i;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if ((reset_read_read_fu_104_p2 == 1'd1)) begin
            dq_t <= 1'd1;
        end else if (((state_load_load_fu_269_p1 == 3'd1) & (reset_read_read_fu_104_p2 == 1'd0))) begin
            dq_t <= 1'd1;
        end else if (((state_load_load_fu_269_p1 == 3'd0) & (reset_read_read_fu_104_p2 == 1'd0))) begin
            dq_t <= 1'd1;
        end else if (((state_load_load_fu_269_p1 == 3'd2) & (reset_read_read_fu_104_p2 == 1'd0))) begin
            dq_t <= 1'd0;
        end else if ((1'b1 == ap_condition_77)) begin
            dq_t <= 1'd1;
        end else if (((state_load_load_fu_269_p1 == 3'd4) & (reset_read_read_fu_104_p2 == 1'd0))) begin
            dq_t <= 1'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((state_load_load_fu_269_p1 == 3'd1) & (1'b1 == ap_CS_fsm_state1) & (reset_read_read_fu_104_p2 == 1'd0)) | ((1'b1 == ap_CS_fsm_state1) & (reset_read_read_fu_104_p2 == 1'd1)))) begin
        next_state <= 3'd0;
    end else if (((state_load_load_fu_269_p1 == 3'd0) & (1'b1 == ap_CS_fsm_state1) & (reset_read_read_fu_104_p2 == 1'd0))) begin
        next_state <= zext_ln61_fu_397_p1;
    end else if (((state_load_load_fu_269_p1 == 3'd2) & (1'b1 == ap_CS_fsm_state1) & (reset_read_read_fu_104_p2 == 1'd0))) begin
        next_state <= select_ln62_1_fu_361_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (((state_load_load_fu_269_p1 == 3'd5) & (reset_read_read_fu_104_p2 == 1'd0)) | ((state_load_load_fu_269_p1 == 3'd3) & (reset_read_read_fu_104_p2 == 1'd0))))) begin
        next_state <= ap_phi_mux_storemerge1_phi_fu_235_p4;
    end else if (((state_load_load_fu_269_p1 == 3'd4) & (1'b1 == ap_CS_fsm_state1) & (reset_read_read_fu_104_p2 == 1'd0))) begin
        next_state <= select_ln64_1_fu_298_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        state <= ap_phi_mux_empty_phi_fu_256_p4;
    end
end

always @ (*) begin
    if (((state_load_load_fu_269_p1 == 3'd1) & (1'b1 == ap_CS_fsm_state1) & (reset_read_read_fu_104_p2 == 1'd0))) begin
        Ce2 = 1'd0;
    end else if ((((state_load_load_fu_269_p1 == 3'd0) & (1'b1 == ap_CS_fsm_state1) & (reset_read_read_fu_104_p2 == 1'd0)) | ((state_load_load_fu_269_p1 == 3'd2) & (1'b1 == ap_CS_fsm_state1) & (reset_read_read_fu_104_p2 == 1'd0)) | ((state_load_load_fu_269_p1 == 3'd4) & (1'b1 == ap_CS_fsm_state1) & (reset_read_read_fu_104_p2 == 1'd0)) | ((1'b1 == ap_CS_fsm_state1) & (((state_load_load_fu_269_p1 == 3'd5) & (reset_read_read_fu_104_p2 == 1'd0)) | ((state_load_load_fu_269_p1 == 3'd3) & (reset_read_read_fu_104_p2 == 1'd0)))))) begin
        Ce2 = 1'd1;
    end else begin
        Ce2 = 'bx;
    end
end

always @ (*) begin
    if (((state_load_load_fu_269_p1 == 3'd1) & (1'b1 == ap_CS_fsm_state1) & (reset_read_read_fu_104_p2 == 1'd0))) begin
        Ce2_n = 1'd1;
    end else if ((((state_load_load_fu_269_p1 == 3'd0) & (1'b1 == ap_CS_fsm_state1) & (reset_read_read_fu_104_p2 == 1'd0)) | ((state_load_load_fu_269_p1 == 3'd2) & (1'b1 == ap_CS_fsm_state1) & (reset_read_read_fu_104_p2 == 1'd0)) | ((state_load_load_fu_269_p1 == 3'd4) & (1'b1 == ap_CS_fsm_state1) & (reset_read_read_fu_104_p2 == 1'd0)) | ((1'b1 == ap_CS_fsm_state1) & (((state_load_load_fu_269_p1 == 3'd5) & (reset_read_read_fu_104_p2 == 1'd0)) | ((state_load_load_fu_269_p1 == 3'd3) & (reset_read_read_fu_104_p2 == 1'd0)))))) begin
        Ce2_n = 1'd0;
    end else begin
        Ce2_n = 'bx;
    end
end

always @ (*) begin
    if (((state_load_load_fu_269_p1 == 3'd1) & (1'b1 == ap_CS_fsm_state1) & (reset_read_read_fu_104_p2 == 1'd0))) begin
        Ce_n = 1'd1;
    end else if ((((state_load_load_fu_269_p1 == 3'd0) & (1'b1 == ap_CS_fsm_state1) & (reset_read_read_fu_104_p2 == 1'd0)) | ((state_load_load_fu_269_p1 == 3'd2) & (1'b1 == ap_CS_fsm_state1) & (reset_read_read_fu_104_p2 == 1'd0)) | ((state_load_load_fu_269_p1 == 3'd4) & (1'b1 == ap_CS_fsm_state1) & (reset_read_read_fu_104_p2 == 1'd0)) | ((1'b1 == ap_CS_fsm_state1) & (((state_load_load_fu_269_p1 == 3'd5) & (reset_read_read_fu_104_p2 == 1'd0)) | ((state_load_load_fu_269_p1 == 3'd3) & (reset_read_read_fu_104_p2 == 1'd0)))))) begin
        Ce_n = 1'd0;
    end else begin
        Ce_n = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (reset_read_read_fu_104_p2 == 1'd0) & (dq_t_load_load_fu_482_p1 == 1'd0))) begin
        Dq_o = data_in;
    end else begin
        Dq_o = Dq_i;
    end
end

always @ (*) begin
    if ((((state_load_load_fu_269_p1 == 3'd1) & (1'b1 == ap_CS_fsm_state1) & (reset_read_read_fu_104_p2 == 1'd0)) | ((state_load_load_fu_269_p1 == 3'd0) & (1'b1 == ap_CS_fsm_state1) & (reset_read_read_fu_104_p2 == 1'd0)) | ((state_load_load_fu_269_p1 == 3'd2) & (1'b1 == ap_CS_fsm_state1) & (reset_read_read_fu_104_p2 == 1'd0)))) begin
        Ld_n = 1'd0;
    end else if (((1'b1 == ap_CS_fsm_state1) & (((state_load_load_fu_269_p1 == 3'd5) & (reset_read_read_fu_104_p2 == 1'd0)) | ((state_load_load_fu_269_p1 == 3'd3) & (reset_read_read_fu_104_p2 == 1'd0))))) begin
        Ld_n = ap_phi_mux_storemerge_phi_fu_244_p4;
    end else if (((state_load_load_fu_269_p1 == 3'd4) & (1'b1 == ap_CS_fsm_state1) & (reset_read_read_fu_104_p2 == 1'd0))) begin
        Ld_n = 1'd1;
    end else begin
        Ld_n = 'bx;
    end
end

always @ (*) begin
    if ((((state_load_load_fu_269_p1 == 3'd1) & (1'b1 == ap_CS_fsm_state1) & (reset_read_read_fu_104_p2 == 1'd0)) | ((state_load_load_fu_269_p1 == 3'd0) & (1'b1 == ap_CS_fsm_state1) & (reset_read_read_fu_104_p2 == 1'd0)) | ((1'b1 == ap_CS_fsm_state1) & (((state_load_load_fu_269_p1 == 3'd5) & (reset_read_read_fu_104_p2 == 1'd0)) | ((state_load_load_fu_269_p1 == 3'd3) & (reset_read_read_fu_104_p2 == 1'd0)))))) begin
        Rw_n = 1'd1;
    end else if ((((state_load_load_fu_269_p1 == 3'd2) & (1'b1 == ap_CS_fsm_state1) & (reset_read_read_fu_104_p2 == 1'd0)) | ((state_load_load_fu_269_p1 == 3'd4) & (1'b1 == ap_CS_fsm_state1) & (reset_read_read_fu_104_p2 == 1'd0)))) begin
        Rw_n = 1'd0;
    end else begin
        Rw_n = 'bx;
    end
end

assign ap_ST_fsm_state1_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if ((reset_read_read_fu_104_p2 == 1'd1)) begin
            ap_phi_mux_empty_phi_fu_256_p4 = 3'd0;
        end else if ((reset_read_read_fu_104_p2 == 1'd0)) begin
            ap_phi_mux_empty_phi_fu_256_p4 = ap_sig_allocacmp_next_state_load;
        end else begin
            ap_phi_mux_empty_phi_fu_256_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_empty_phi_fu_256_p4 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (reset_read_read_fu_104_p2 == 1'd0))) begin
        if ((state_load_load_fu_269_p1 == 3'd5)) begin
            ap_phi_mux_storemerge1_phi_fu_235_p4 = select_ln65_1_fu_281_p3;
        end else if ((state_load_load_fu_269_p1 == 3'd3)) begin
            ap_phi_mux_storemerge1_phi_fu_235_p4 = select_ln63_1_fu_326_p3;
        end else begin
            ap_phi_mux_storemerge1_phi_fu_235_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_storemerge1_phi_fu_235_p4 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (reset_read_read_fu_104_p2 == 1'd0))) begin
        if ((state_load_load_fu_269_p1 == 3'd5)) begin
            ap_phi_mux_storemerge_phi_fu_244_p4 = 1'd1;
        end else if ((state_load_load_fu_269_p1 == 3'd3)) begin
            ap_phi_mux_storemerge_phi_fu_244_p4 = 1'd0;
        end else begin
            ap_phi_mux_storemerge_phi_fu_244_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_storemerge_phi_fu_244_p4 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (((reset_read_read_fu_104_p2 == 1'd0) & (1'd1 == and_ln96_fu_442_p2)) | ((reset_read_read_fu_104_p2 == 1'd0) & (1'd1 == and_ln98_fu_460_p2))))) begin
        ap_sig_allocacmp_addr_reg_V_load = addr_in;
    end else begin
        ap_sig_allocacmp_addr_reg_V_load = addr_reg_V;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (((state_load_load_fu_269_p1 == 3'd5) & (reset_read_read_fu_104_p2 == 1'd0)) | ((state_load_load_fu_269_p1 == 3'd3) & (reset_read_read_fu_104_p2 == 1'd0))))) begin
        ap_sig_allocacmp_data_out_reg_V_load = Dq_i;
    end else begin
        ap_sig_allocacmp_data_out_reg_V_load = data_out_reg_V;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if (((state_load_load_fu_269_p1 == 3'd1) & (reset_read_read_fu_104_p2 == 1'd0))) begin
            ap_sig_allocacmp_dq_t_load = 1'd1;
        end else if (((state_load_load_fu_269_p1 == 3'd0) & (reset_read_read_fu_104_p2 == 1'd0))) begin
            ap_sig_allocacmp_dq_t_load = 1'd1;
        end else if (((state_load_load_fu_269_p1 == 3'd2) & (reset_read_read_fu_104_p2 == 1'd0))) begin
            ap_sig_allocacmp_dq_t_load = 1'd0;
        end else if ((1'b1 == ap_condition_77)) begin
            ap_sig_allocacmp_dq_t_load = 1'd1;
        end else if (((state_load_load_fu_269_p1 == 3'd4) & (reset_read_read_fu_104_p2 == 1'd0))) begin
            ap_sig_allocacmp_dq_t_load = 1'd0;
        end else begin
            ap_sig_allocacmp_dq_t_load = dq_t;
        end
    end else begin
        ap_sig_allocacmp_dq_t_load = dq_t;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if (((state_load_load_fu_269_p1 == 3'd1) & (reset_read_read_fu_104_p2 == 1'd0))) begin
            ap_sig_allocacmp_next_state_load = 3'd0;
        end else if (((state_load_load_fu_269_p1 == 3'd0) & (reset_read_read_fu_104_p2 == 1'd0))) begin
            ap_sig_allocacmp_next_state_load = zext_ln61_fu_397_p1;
        end else if (((state_load_load_fu_269_p1 == 3'd2) & (reset_read_read_fu_104_p2 == 1'd0))) begin
            ap_sig_allocacmp_next_state_load = select_ln62_1_fu_361_p3;
        end else if ((1'b1 == ap_condition_77)) begin
            ap_sig_allocacmp_next_state_load = ap_phi_mux_storemerge1_phi_fu_235_p4;
        end else if (((state_load_load_fu_269_p1 == 3'd4) & (reset_read_read_fu_104_p2 == 1'd0))) begin
            ap_sig_allocacmp_next_state_load = select_ln64_1_fu_298_p3;
        end else begin
            ap_sig_allocacmp_next_state_load = next_state;
        end
    end else begin
        ap_sig_allocacmp_next_state_load = next_state;
    end
end

always @ (*) begin
    if (((state_load_load_fu_269_p1 == 3'd0) & (1'b1 == ap_CS_fsm_state1) & (reset_read_read_fu_104_p2 == 1'd0))) begin
        ready_r = 1'd1;
    end else if ((((state_load_load_fu_269_p1 == 3'd1) & (1'b1 == ap_CS_fsm_state1) & (reset_read_read_fu_104_p2 == 1'd0)) | ((state_load_load_fu_269_p1 == 3'd2) & (1'b1 == ap_CS_fsm_state1) & (reset_read_read_fu_104_p2 == 1'd0)) | ((state_load_load_fu_269_p1 == 3'd4) & (1'b1 == ap_CS_fsm_state1) & (reset_read_read_fu_104_p2 == 1'd0)) | ((1'b1 == ap_CS_fsm_state1) & (((state_load_load_fu_269_p1 == 3'd5) & (reset_read_read_fu_104_p2 == 1'd0)) | ((state_load_load_fu_269_p1 == 3'd3) & (reset_read_read_fu_104_p2 == 1'd0)))) | ((1'b1 == ap_CS_fsm_state1) & (reset_read_read_fu_104_p2 == 1'd1)))) begin
        ready_r = 1'd0;
    end else begin
        ready_r = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Addr = ap_sig_allocacmp_addr_reg_V_load;

assign Cke_n = 1'd0;

assign Oe_n = 1'd0;

assign and_ln96_fu_442_p2 = (icmp_ln96_fu_430_p2 & icmp_ln96_1_fu_436_p2);

assign and_ln98_fu_460_p2 = (icmp_ln98_fu_448_p2 & icmp_ln98_1_fu_454_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_condition_101 = (((reset_read_read_fu_104_p2 == 1'd0) & (1'd1 == and_ln96_fu_442_p2)) | ((reset_read_read_fu_104_p2 == 1'd0) & (1'd1 == and_ln98_fu_460_p2)));
end

always @ (*) begin
    ap_condition_77 = (((state_load_load_fu_269_p1 == 3'd5) & (reset_read_read_fu_104_p2 == 1'd0)) | ((state_load_load_fu_269_p1 == 3'd3) & (reset_read_read_fu_104_p2 == 1'd0)));
end

assign ap_local_block = 1'b0;

assign ap_local_deadlock = 1'b0;

assign data_out = ap_sig_allocacmp_data_out_reg_V_load;

assign dq_t_load_load_fu_482_p1 = ap_sig_allocacmp_dq_t_load;

assign icmp_ln96_1_fu_436_p2 = ((state != 3'd4) ? 1'b1 : 1'b0);

assign icmp_ln96_fu_430_p2 = ((ap_sig_allocacmp_next_state_load == 3'd4) ? 1'b1 : 1'b0);

assign icmp_ln98_1_fu_454_p2 = ((state != 3'd5) ? 1'b1 : 1'b0);

assign icmp_ln98_fu_448_p2 = ((ap_sig_allocacmp_next_state_load == 3'd5) ? 1'b1 : 1'b0);

assign or_ln61_fu_263_p0 = we;

assign or_ln61_fu_263_p1 = re;

assign or_ln61_fu_263_p2 = (or_ln61_fu_263_p1 | or_ln61_fu_263_p0);

assign reset_read_read_fu_104_p2 = reset;

assign select_ln61_1_fu_389_p3 = ((or_ln61_fu_263_p2[0:0] == 1'b1) ? select_ln61_fu_381_p3 : 2'd0);

assign select_ln61_fu_381_p0 = we;

assign select_ln61_fu_381_p3 = ((select_ln61_fu_381_p0[0:0] == 1'b1) ? 2'd2 : 2'd3);

assign select_ln62_1_fu_361_p3 = ((or_ln61_fu_263_p2[0:0] == 1'b1) ? select_ln62_fu_353_p3 : 3'd0);

assign select_ln62_fu_353_p0 = we;

assign select_ln62_fu_353_p3 = ((select_ln62_fu_353_p0[0:0] == 1'b1) ? 3'd4 : 3'd3);

assign select_ln63_1_fu_326_p3 = ((or_ln61_fu_263_p2[0:0] == 1'b1) ? select_ln63_fu_318_p3 : 3'd0);

assign select_ln63_fu_318_p0 = we;

assign select_ln63_fu_318_p3 = ((select_ln63_fu_318_p0[0:0] == 1'b1) ? 3'd2 : 3'd5);

assign select_ln64_1_fu_298_p3 = ((or_ln61_fu_263_p2[0:0] == 1'b1) ? select_ln64_fu_290_p3 : 3'd0);

assign select_ln64_fu_290_p0 = we;

assign select_ln64_fu_290_p3 = ((select_ln64_fu_290_p0[0:0] == 1'b1) ? 3'd4 : 3'd3);

assign select_ln65_1_fu_281_p3 = ((or_ln61_fu_263_p2[0:0] == 1'b1) ? select_ln65_fu_273_p3 : 3'd0);

assign select_ln65_fu_273_p0 = we;

assign select_ln65_fu_273_p3 = ((select_ln65_fu_273_p0[0:0] == 1'b1) ? 3'd2 : 3'd5);

assign state_load_load_fu_269_p1 = state;

assign zext_ln61_fu_397_p1 = select_ln61_1_fu_389_p3;

endmodule //control_SRAM_HLS
