-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
-- Version: 2021.2
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity control_SRAM_HLS is
port (
    ap_local_block : OUT STD_LOGIC;
    ap_local_deadlock : OUT STD_LOGIC;
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    addr_in : IN STD_LOGIC_VECTOR (18 downto 0);
    data_in : IN STD_LOGIC_VECTOR (35 downto 0);
    data_out : OUT STD_LOGIC_VECTOR (35 downto 0);
    we : IN STD_LOGIC;
    re : IN STD_LOGIC;
    ready_r : OUT STD_LOGIC;
    Addr : OUT STD_LOGIC_VECTOR (18 downto 0);
    Dq_i : IN STD_LOGIC_VECTOR (35 downto 0);
    Dq_o : OUT STD_LOGIC_VECTOR (35 downto 0);
    Ce_n : OUT STD_LOGIC;
    Ce2 : OUT STD_LOGIC;
    Ce2_n : OUT STD_LOGIC;
    Oe_n : OUT STD_LOGIC;
    Rw_n : OUT STD_LOGIC;
    Ld_n : OUT STD_LOGIC;
    Cke_n : OUT STD_LOGIC;
    clk : IN STD_LOGIC;
    reset : IN STD_LOGIC );
end;


architecture behav of control_SRAM_HLS is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "control_SRAM_HLS_control_SRAM_HLS,hls_ip_2021_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu5p-flva2104-1-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=1.539429,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=63,HLS_SYN_LUT=340,HLS_VERSION=2021_2}";
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv19_0 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000000000000";
    constant ap_const_lv36_0 : STD_LOGIC_VECTOR (35 downto 0) := "000000000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv1_0_1 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1_2 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0_3 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1_4 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_1_5 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_1_6 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";

    signal next_state : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal addr_reg_V : STD_LOGIC_VECTOR (18 downto 0) := "0000000000000000000";
    signal data_out_reg_V : STD_LOGIC_VECTOR (35 downto 0) := "000000000000000000000000000000000000";
    signal dq_t : STD_LOGIC_VECTOR (0 downto 0) := "1";
    signal state : STD_LOGIC_VECTOR (2 downto 0) := "001";
    signal select_ln63_1_fu_326_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_mux_storemerge1_phi_fu_235_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal reset_read_read_fu_104_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal state_load_load_fu_269_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln65_1_fu_281_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_mux_storemerge_phi_fu_244_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_empty_phi_fu_256_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln64_1_fu_298_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln62_1_fu_361_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln61_fu_397_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_sig_allocacmp_next_state_load : STD_LOGIC_VECTOR (2 downto 0);
    signal and_ln98_fu_460_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln96_fu_442_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_allocacmp_addr_reg_V_load : STD_LOGIC_VECTOR (18 downto 0);
    signal ap_sig_allocacmp_data_out_reg_V_load : STD_LOGIC_VECTOR (35 downto 0);
    signal ap_sig_allocacmp_dq_t_load : STD_LOGIC_VECTOR (0 downto 0);
    signal dq_t_load_load_fu_482_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln61_fu_263_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln61_fu_263_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln65_fu_273_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln61_fu_263_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln65_fu_273_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln64_fu_290_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln64_fu_290_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln63_fu_318_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln63_fu_318_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln62_fu_353_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln62_fu_353_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln61_fu_381_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln61_fu_381_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln61_1_fu_389_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln96_fu_430_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln96_1_fu_436_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln98_fu_448_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln98_1_fu_454_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_condition_101 : BOOLEAN;
    signal ap_condition_77 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    addr_reg_V_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                if ((reset_read_read_fu_104_p2 = ap_const_lv1_1)) then 
                    addr_reg_V <= ap_const_lv19_0;
                elsif ((ap_const_boolean_1 = ap_condition_101)) then 
                    addr_reg_V <= addr_in;
                end if;
            end if; 
        end if;
    end process;

    data_out_reg_V_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                if ((reset_read_read_fu_104_p2 = ap_const_lv1_1)) then 
                    data_out_reg_V <= ap_const_lv36_0;
                elsif ((ap_const_boolean_1 = ap_condition_77)) then 
                    data_out_reg_V <= Dq_i;
                end if;
            end if; 
        end if;
    end process;

    dq_t_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                if ((reset_read_read_fu_104_p2 = ap_const_lv1_1)) then 
                    dq_t <= ap_const_lv1_1_6;
                elsif (((state_load_load_fu_269_p1 = ap_const_lv3_1) and (reset_read_read_fu_104_p2 = ap_const_lv1_0))) then 
                    dq_t <= ap_const_lv1_1_5;
                elsif (((state_load_load_fu_269_p1 = ap_const_lv3_0) and (reset_read_read_fu_104_p2 = ap_const_lv1_0))) then 
                    dq_t <= ap_const_lv1_1_4;
                elsif (((state_load_load_fu_269_p1 = ap_const_lv3_2) and (reset_read_read_fu_104_p2 = ap_const_lv1_0))) then 
                    dq_t <= ap_const_lv1_0_3;
                elsif ((ap_const_boolean_1 = ap_condition_77)) then 
                    dq_t <= ap_const_lv1_1_2;
                elsif (((state_load_load_fu_269_p1 = ap_const_lv3_4) and (reset_read_read_fu_104_p2 = ap_const_lv1_0))) then 
                    dq_t <= ap_const_lv1_0_1;
                end if;
            end if; 
        end if;
    end process;

    next_state_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((state_load_load_fu_269_p1 = ap_const_lv3_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (reset_read_read_fu_104_p2 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (reset_read_read_fu_104_p2 = ap_const_lv1_1)))) then 
                next_state <= ap_const_lv3_0;
            elsif (((state_load_load_fu_269_p1 = ap_const_lv3_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (reset_read_read_fu_104_p2 = ap_const_lv1_0))) then 
                next_state <= zext_ln61_fu_397_p1;
            elsif (((state_load_load_fu_269_p1 = ap_const_lv3_2) and (ap_const_logic_1 = ap_CS_fsm_state1) and (reset_read_read_fu_104_p2 = ap_const_lv1_0))) then 
                next_state <= select_ln62_1_fu_361_p3;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (((state_load_load_fu_269_p1 = ap_const_lv3_5) and (reset_read_read_fu_104_p2 = ap_const_lv1_0)) or ((state_load_load_fu_269_p1 = ap_const_lv3_3) and (reset_read_read_fu_104_p2 = ap_const_lv1_0))))) then 
                next_state <= ap_phi_mux_storemerge1_phi_fu_235_p4;
            elsif (((state_load_load_fu_269_p1 = ap_const_lv3_4) and (ap_const_logic_1 = ap_CS_fsm_state1) and (reset_read_read_fu_104_p2 = ap_const_lv1_0))) then 
                next_state <= select_ln64_1_fu_298_p3;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                state <= ap_phi_mux_empty_phi_fu_256_p4;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    Addr <= ap_sig_allocacmp_addr_reg_V_load;

    Ce2_assign_proc : process(ap_CS_fsm_state1, reset_read_read_fu_104_p2, state_load_load_fu_269_p1)
    begin
        if (((state_load_load_fu_269_p1 = ap_const_lv3_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (reset_read_read_fu_104_p2 = ap_const_lv1_0))) then 
            Ce2 <= ap_const_logic_0;
        elsif ((((state_load_load_fu_269_p1 = ap_const_lv3_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (reset_read_read_fu_104_p2 = ap_const_lv1_0)) or ((state_load_load_fu_269_p1 = ap_const_lv3_2) and (ap_const_logic_1 = ap_CS_fsm_state1) and (reset_read_read_fu_104_p2 = ap_const_lv1_0)) or ((state_load_load_fu_269_p1 = ap_const_lv3_4) and (ap_const_logic_1 = ap_CS_fsm_state1) and (reset_read_read_fu_104_p2 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (((state_load_load_fu_269_p1 = ap_const_lv3_5) and (reset_read_read_fu_104_p2 = ap_const_lv1_0)) or ((state_load_load_fu_269_p1 = ap_const_lv3_3) and (reset_read_read_fu_104_p2 = ap_const_lv1_0)))))) then 
            Ce2 <= ap_const_logic_1;
        else 
            Ce2 <= 'X';
        end if; 
    end process;


    Ce2_n_assign_proc : process(ap_CS_fsm_state1, reset_read_read_fu_104_p2, state_load_load_fu_269_p1)
    begin
        if (((state_load_load_fu_269_p1 = ap_const_lv3_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (reset_read_read_fu_104_p2 = ap_const_lv1_0))) then 
            Ce2_n <= ap_const_logic_1;
        elsif ((((state_load_load_fu_269_p1 = ap_const_lv3_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (reset_read_read_fu_104_p2 = ap_const_lv1_0)) or ((state_load_load_fu_269_p1 = ap_const_lv3_2) and (ap_const_logic_1 = ap_CS_fsm_state1) and (reset_read_read_fu_104_p2 = ap_const_lv1_0)) or ((state_load_load_fu_269_p1 = ap_const_lv3_4) and (ap_const_logic_1 = ap_CS_fsm_state1) and (reset_read_read_fu_104_p2 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (((state_load_load_fu_269_p1 = ap_const_lv3_5) and (reset_read_read_fu_104_p2 = ap_const_lv1_0)) or ((state_load_load_fu_269_p1 = ap_const_lv3_3) and (reset_read_read_fu_104_p2 = ap_const_lv1_0)))))) then 
            Ce2_n <= ap_const_logic_0;
        else 
            Ce2_n <= 'X';
        end if; 
    end process;


    Ce_n_assign_proc : process(ap_CS_fsm_state1, reset_read_read_fu_104_p2, state_load_load_fu_269_p1)
    begin
        if (((state_load_load_fu_269_p1 = ap_const_lv3_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (reset_read_read_fu_104_p2 = ap_const_lv1_0))) then 
            Ce_n <= ap_const_logic_1;
        elsif ((((state_load_load_fu_269_p1 = ap_const_lv3_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (reset_read_read_fu_104_p2 = ap_const_lv1_0)) or ((state_load_load_fu_269_p1 = ap_const_lv3_2) and (ap_const_logic_1 = ap_CS_fsm_state1) and (reset_read_read_fu_104_p2 = ap_const_lv1_0)) or ((state_load_load_fu_269_p1 = ap_const_lv3_4) and (ap_const_logic_1 = ap_CS_fsm_state1) and (reset_read_read_fu_104_p2 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (((state_load_load_fu_269_p1 = ap_const_lv3_5) and (reset_read_read_fu_104_p2 = ap_const_lv1_0)) or ((state_load_load_fu_269_p1 = ap_const_lv3_3) and (reset_read_read_fu_104_p2 = ap_const_lv1_0)))))) then 
            Ce_n <= ap_const_logic_0;
        else 
            Ce_n <= 'X';
        end if; 
    end process;

    Cke_n <= ap_const_logic_0;

    Dq_o_assign_proc : process(data_in, Dq_i, ap_CS_fsm_state1, reset_read_read_fu_104_p2, dq_t_load_load_fu_482_p1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (reset_read_read_fu_104_p2 = ap_const_lv1_0) and (dq_t_load_load_fu_482_p1 = ap_const_lv1_0))) then 
            Dq_o <= data_in;
        else 
            Dq_o <= Dq_i;
        end if; 
    end process;


    Ld_n_assign_proc : process(ap_CS_fsm_state1, reset_read_read_fu_104_p2, state_load_load_fu_269_p1, ap_phi_mux_storemerge_phi_fu_244_p4)
    begin
        if ((((state_load_load_fu_269_p1 = ap_const_lv3_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (reset_read_read_fu_104_p2 = ap_const_lv1_0)) or ((state_load_load_fu_269_p1 = ap_const_lv3_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (reset_read_read_fu_104_p2 = ap_const_lv1_0)) or ((state_load_load_fu_269_p1 = ap_const_lv3_2) and (ap_const_logic_1 = ap_CS_fsm_state1) and (reset_read_read_fu_104_p2 = ap_const_lv1_0)))) then 
            Ld_n <= ap_const_logic_0;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (((state_load_load_fu_269_p1 = ap_const_lv3_5) and (reset_read_read_fu_104_p2 = ap_const_lv1_0)) or ((state_load_load_fu_269_p1 = ap_const_lv3_3) and (reset_read_read_fu_104_p2 = ap_const_lv1_0))))) then 
            Ld_n <= ap_phi_mux_storemerge_phi_fu_244_p4(0);
        elsif (((state_load_load_fu_269_p1 = ap_const_lv3_4) and (ap_const_logic_1 = ap_CS_fsm_state1) and (reset_read_read_fu_104_p2 = ap_const_lv1_0))) then 
            Ld_n <= ap_const_logic_1;
        else 
            Ld_n <= 'X';
        end if; 
    end process;

    Oe_n <= ap_const_logic_0;

    Rw_n_assign_proc : process(ap_CS_fsm_state1, reset_read_read_fu_104_p2, state_load_load_fu_269_p1)
    begin
        if ((((state_load_load_fu_269_p1 = ap_const_lv3_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (reset_read_read_fu_104_p2 = ap_const_lv1_0)) or ((state_load_load_fu_269_p1 = ap_const_lv3_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (reset_read_read_fu_104_p2 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (((state_load_load_fu_269_p1 = ap_const_lv3_5) and (reset_read_read_fu_104_p2 = ap_const_lv1_0)) or ((state_load_load_fu_269_p1 = ap_const_lv3_3) and (reset_read_read_fu_104_p2 = ap_const_lv1_0)))))) then 
            Rw_n <= ap_const_logic_1;
        elsif ((((state_load_load_fu_269_p1 = ap_const_lv3_2) and (ap_const_logic_1 = ap_CS_fsm_state1) and (reset_read_read_fu_104_p2 = ap_const_lv1_0)) or ((state_load_load_fu_269_p1 = ap_const_lv3_4) and (ap_const_logic_1 = ap_CS_fsm_state1) and (reset_read_read_fu_104_p2 = ap_const_lv1_0)))) then 
            Rw_n <= ap_const_logic_0;
        else 
            Rw_n <= 'X';
        end if; 
    end process;

    and_ln96_fu_442_p2 <= (icmp_ln96_fu_430_p2 and icmp_ln96_1_fu_436_p2);
    and_ln98_fu_460_p2 <= (icmp_ln98_fu_448_p2 and icmp_ln98_1_fu_454_p2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_ST_fsm_state1_blk <= ap_const_logic_0;

    ap_condition_101_assign_proc : process(reset_read_read_fu_104_p2, and_ln98_fu_460_p2, and_ln96_fu_442_p2)
    begin
                ap_condition_101 <= (((reset_read_read_fu_104_p2 = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln96_fu_442_p2)) or ((reset_read_read_fu_104_p2 = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln98_fu_460_p2)));
    end process;


    ap_condition_77_assign_proc : process(reset_read_read_fu_104_p2, state_load_load_fu_269_p1)
    begin
                ap_condition_77 <= (((state_load_load_fu_269_p1 = ap_const_lv3_5) and (reset_read_read_fu_104_p2 = ap_const_lv1_0)) or ((state_load_load_fu_269_p1 = ap_const_lv3_3) and (reset_read_read_fu_104_p2 = ap_const_lv1_0)));
    end process;

    ap_local_block <= ap_const_logic_0;
    ap_local_deadlock <= ap_const_logic_0;

    ap_phi_mux_empty_phi_fu_256_p4_assign_proc : process(ap_CS_fsm_state1, reset_read_read_fu_104_p2, ap_sig_allocacmp_next_state_load)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
            if ((reset_read_read_fu_104_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_empty_phi_fu_256_p4 <= ap_const_lv3_0;
            elsif ((reset_read_read_fu_104_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_empty_phi_fu_256_p4 <= ap_sig_allocacmp_next_state_load;
            else 
                ap_phi_mux_empty_phi_fu_256_p4 <= "XXX";
            end if;
        else 
            ap_phi_mux_empty_phi_fu_256_p4 <= "XXX";
        end if; 
    end process;


    ap_phi_mux_storemerge1_phi_fu_235_p4_assign_proc : process(select_ln63_1_fu_326_p3, ap_CS_fsm_state1, reset_read_read_fu_104_p2, state_load_load_fu_269_p1, select_ln65_1_fu_281_p3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (reset_read_read_fu_104_p2 = ap_const_lv1_0))) then
            if ((state_load_load_fu_269_p1 = ap_const_lv3_5)) then 
                ap_phi_mux_storemerge1_phi_fu_235_p4 <= select_ln65_1_fu_281_p3;
            elsif ((state_load_load_fu_269_p1 = ap_const_lv3_3)) then 
                ap_phi_mux_storemerge1_phi_fu_235_p4 <= select_ln63_1_fu_326_p3;
            else 
                ap_phi_mux_storemerge1_phi_fu_235_p4 <= "XXX";
            end if;
        else 
            ap_phi_mux_storemerge1_phi_fu_235_p4 <= "XXX";
        end if; 
    end process;


    ap_phi_mux_storemerge_phi_fu_244_p4_assign_proc : process(ap_CS_fsm_state1, reset_read_read_fu_104_p2, state_load_load_fu_269_p1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (reset_read_read_fu_104_p2 = ap_const_lv1_0))) then
            if ((state_load_load_fu_269_p1 = ap_const_lv3_5)) then 
                ap_phi_mux_storemerge_phi_fu_244_p4 <= ap_const_lv1_1;
            elsif ((state_load_load_fu_269_p1 = ap_const_lv3_3)) then 
                ap_phi_mux_storemerge_phi_fu_244_p4 <= ap_const_lv1_0;
            else 
                ap_phi_mux_storemerge_phi_fu_244_p4 <= "X";
            end if;
        else 
            ap_phi_mux_storemerge_phi_fu_244_p4 <= "X";
        end if; 
    end process;


    ap_sig_allocacmp_addr_reg_V_load_assign_proc : process(addr_in, addr_reg_V, ap_CS_fsm_state1, reset_read_read_fu_104_p2, and_ln98_fu_460_p2, and_ln96_fu_442_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (((reset_read_read_fu_104_p2 = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln96_fu_442_p2)) or ((reset_read_read_fu_104_p2 = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln98_fu_460_p2))))) then 
            ap_sig_allocacmp_addr_reg_V_load <= addr_in;
        else 
            ap_sig_allocacmp_addr_reg_V_load <= addr_reg_V;
        end if; 
    end process;


    ap_sig_allocacmp_data_out_reg_V_load_assign_proc : process(Dq_i, data_out_reg_V, ap_CS_fsm_state1, reset_read_read_fu_104_p2, state_load_load_fu_269_p1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (((state_load_load_fu_269_p1 = ap_const_lv3_5) and (reset_read_read_fu_104_p2 = ap_const_lv1_0)) or ((state_load_load_fu_269_p1 = ap_const_lv3_3) and (reset_read_read_fu_104_p2 = ap_const_lv1_0))))) then 
            ap_sig_allocacmp_data_out_reg_V_load <= Dq_i;
        else 
            ap_sig_allocacmp_data_out_reg_V_load <= data_out_reg_V;
        end if; 
    end process;


    ap_sig_allocacmp_dq_t_load_assign_proc : process(dq_t, ap_CS_fsm_state1, reset_read_read_fu_104_p2, state_load_load_fu_269_p1, ap_condition_77)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
            if (((state_load_load_fu_269_p1 = ap_const_lv3_1) and (reset_read_read_fu_104_p2 = ap_const_lv1_0))) then 
                ap_sig_allocacmp_dq_t_load <= ap_const_lv1_1_5;
            elsif (((state_load_load_fu_269_p1 = ap_const_lv3_0) and (reset_read_read_fu_104_p2 = ap_const_lv1_0))) then 
                ap_sig_allocacmp_dq_t_load <= ap_const_lv1_1_4;
            elsif (((state_load_load_fu_269_p1 = ap_const_lv3_2) and (reset_read_read_fu_104_p2 = ap_const_lv1_0))) then 
                ap_sig_allocacmp_dq_t_load <= ap_const_lv1_0_3;
            elsif ((ap_const_boolean_1 = ap_condition_77)) then 
                ap_sig_allocacmp_dq_t_load <= ap_const_lv1_1_2;
            elsif (((state_load_load_fu_269_p1 = ap_const_lv3_4) and (reset_read_read_fu_104_p2 = ap_const_lv1_0))) then 
                ap_sig_allocacmp_dq_t_load <= ap_const_lv1_0_1;
            else 
                ap_sig_allocacmp_dq_t_load <= dq_t;
            end if;
        else 
            ap_sig_allocacmp_dq_t_load <= dq_t;
        end if; 
    end process;


    ap_sig_allocacmp_next_state_load_assign_proc : process(next_state, ap_phi_mux_storemerge1_phi_fu_235_p4, ap_CS_fsm_state1, reset_read_read_fu_104_p2, state_load_load_fu_269_p1, select_ln64_1_fu_298_p3, select_ln62_1_fu_361_p3, zext_ln61_fu_397_p1, ap_condition_77)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
            if (((state_load_load_fu_269_p1 = ap_const_lv3_1) and (reset_read_read_fu_104_p2 = ap_const_lv1_0))) then 
                ap_sig_allocacmp_next_state_load <= ap_const_lv3_0;
            elsif (((state_load_load_fu_269_p1 = ap_const_lv3_0) and (reset_read_read_fu_104_p2 = ap_const_lv1_0))) then 
                ap_sig_allocacmp_next_state_load <= zext_ln61_fu_397_p1;
            elsif (((state_load_load_fu_269_p1 = ap_const_lv3_2) and (reset_read_read_fu_104_p2 = ap_const_lv1_0))) then 
                ap_sig_allocacmp_next_state_load <= select_ln62_1_fu_361_p3;
            elsif ((ap_const_boolean_1 = ap_condition_77)) then 
                ap_sig_allocacmp_next_state_load <= ap_phi_mux_storemerge1_phi_fu_235_p4;
            elsif (((state_load_load_fu_269_p1 = ap_const_lv3_4) and (reset_read_read_fu_104_p2 = ap_const_lv1_0))) then 
                ap_sig_allocacmp_next_state_load <= select_ln64_1_fu_298_p3;
            else 
                ap_sig_allocacmp_next_state_load <= next_state;
            end if;
        else 
            ap_sig_allocacmp_next_state_load <= next_state;
        end if; 
    end process;

    data_out <= ap_sig_allocacmp_data_out_reg_V_load;
    dq_t_load_load_fu_482_p1 <= ap_sig_allocacmp_dq_t_load;
    icmp_ln96_1_fu_436_p2 <= "0" when (state = ap_const_lv3_4) else "1";
    icmp_ln96_fu_430_p2 <= "1" when (ap_sig_allocacmp_next_state_load = ap_const_lv3_4) else "0";
    icmp_ln98_1_fu_454_p2 <= "0" when (state = ap_const_lv3_5) else "1";
    icmp_ln98_fu_448_p2 <= "1" when (ap_sig_allocacmp_next_state_load = ap_const_lv3_5) else "0";
    or_ln61_fu_263_p0 <= (0=>we, others=>'-');
    or_ln61_fu_263_p1 <= (0=>re, others=>'-');
    or_ln61_fu_263_p2 <= (or_ln61_fu_263_p1 or or_ln61_fu_263_p0);

    ready_r_assign_proc : process(ap_CS_fsm_state1, reset_read_read_fu_104_p2, state_load_load_fu_269_p1)
    begin
        if (((state_load_load_fu_269_p1 = ap_const_lv3_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (reset_read_read_fu_104_p2 = ap_const_lv1_0))) then 
            ready_r <= ap_const_logic_1;
        elsif ((((state_load_load_fu_269_p1 = ap_const_lv3_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (reset_read_read_fu_104_p2 = ap_const_lv1_0)) or ((state_load_load_fu_269_p1 = ap_const_lv3_2) and (ap_const_logic_1 = ap_CS_fsm_state1) and (reset_read_read_fu_104_p2 = ap_const_lv1_0)) or ((state_load_load_fu_269_p1 = ap_const_lv3_4) and (ap_const_logic_1 = ap_CS_fsm_state1) and (reset_read_read_fu_104_p2 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (((state_load_load_fu_269_p1 = ap_const_lv3_5) and (reset_read_read_fu_104_p2 = ap_const_lv1_0)) or ((state_load_load_fu_269_p1 = ap_const_lv3_3) and (reset_read_read_fu_104_p2 = ap_const_lv1_0)))) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (reset_read_read_fu_104_p2 = ap_const_lv1_1)))) then 
            ready_r <= ap_const_logic_0;
        else 
            ready_r <= 'X';
        end if; 
    end process;

    reset_read_read_fu_104_p2 <= (0=>reset, others=>'-');
    select_ln61_1_fu_389_p3 <= 
        select_ln61_fu_381_p3 when (or_ln61_fu_263_p2(0) = '1') else 
        ap_const_lv2_0;
    select_ln61_fu_381_p0 <= (0=>we, others=>'-');
    select_ln61_fu_381_p3 <= 
        ap_const_lv2_2 when (select_ln61_fu_381_p0(0) = '1') else 
        ap_const_lv2_3;
    select_ln62_1_fu_361_p3 <= 
        select_ln62_fu_353_p3 when (or_ln61_fu_263_p2(0) = '1') else 
        ap_const_lv3_0;
    select_ln62_fu_353_p0 <= (0=>we, others=>'-');
    select_ln62_fu_353_p3 <= 
        ap_const_lv3_4 when (select_ln62_fu_353_p0(0) = '1') else 
        ap_const_lv3_3;
    select_ln63_1_fu_326_p3 <= 
        select_ln63_fu_318_p3 when (or_ln61_fu_263_p2(0) = '1') else 
        ap_const_lv3_0;
    select_ln63_fu_318_p0 <= (0=>we, others=>'-');
    select_ln63_fu_318_p3 <= 
        ap_const_lv3_2 when (select_ln63_fu_318_p0(0) = '1') else 
        ap_const_lv3_5;
    select_ln64_1_fu_298_p3 <= 
        select_ln64_fu_290_p3 when (or_ln61_fu_263_p2(0) = '1') else 
        ap_const_lv3_0;
    select_ln64_fu_290_p0 <= (0=>we, others=>'-');
    select_ln64_fu_290_p3 <= 
        ap_const_lv3_4 when (select_ln64_fu_290_p0(0) = '1') else 
        ap_const_lv3_3;
    select_ln65_1_fu_281_p3 <= 
        select_ln65_fu_273_p3 when (or_ln61_fu_263_p2(0) = '1') else 
        ap_const_lv3_0;
    select_ln65_fu_273_p0 <= (0=>we, others=>'-');
    select_ln65_fu_273_p3 <= 
        ap_const_lv3_2 when (select_ln65_fu_273_p0(0) = '1') else 
        ap_const_lv3_5;
    state_load_load_fu_269_p1 <= state;
    zext_ln61_fu_397_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln61_1_fu_389_p3),3));
end behav;
